SuffoArt/Controllers/AdminController.cs
using SuffoArt.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuffoArt.Controllers
{
    public class AdminController : Controller
    {
        // Instanciación del modelo
        LoginBD loginModel = new LoginBD();
        MediaBD mediaModel = new MediaBD();


        // GET: Admin
        public ActionResult IniciarSesion()
        {
            if (Session["username"] == null)
            {
                return View();
            }
            else
            {
                Session["username"] = null;
                return View();
            }
        }

        // POST: IniciarSesion
        [HttpPost]
        public ActionResult IniciarSesion(LoginViewModel datos)
        {
            bool error = false;
            try
            {
                if (ModelState.IsValid)
                {
                    if (loginModel.ComprobarLogin(datos))
                    {
                        Session["username"] = "Login Correcto";
                    }
                    else
                    {
                        error = true;
                    }
                }
                else
                {
                    error = true;
                }
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine(e);
                error = true;
            }

            if (error)
            {
                return RedirectToAction("Error");
            }
            else
            {
                return RedirectToAction("PanelDeControl");
            }
        }

        public ActionResult PanelDeControl()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("IniciarSesion");
            }
            else
            {
                return View();
            }
        }

        //public ActionResult AdministrarBlog()
        //{
        //    if (Session["username"] == null)
        //    {
        //        return RedirectToAction("IniciarSesion");
        //    }
        //    else
        //    {
        //        return View();
        //    }
        //}

        public ActionResult AdministrarAnimaciones()
        {
            if (Session["username"] != null)
            {
                if (Session["NumRegistroAnimaciones"] == null)
                {
                    Session["NumRegistroAnimaciones"] = 0;
                }
                List<Media> animaciones = mediaModel.GetAnimacionesPaginated((int)Session["NumRegistroAnimaciones"]);

                return View(animaciones);
            }
            else
            {
                return RedirectToAction("IniciarSesion");
            }
        }

        // GET: ResetNumPaginaAdminAnimaciones()
        public ActionResult ResetNumPaginaAdminAnimaciones()
        {
            Session["NumRegistroAnimaciones"] = null;
            return RedirectToAction("AdministrarAnimaciones");
        }

        // GET: SiguientePaginaAdminAnimaciones()
        public ActionResult SiguientePaginaAdminAnimaciones()
        {
            if (Session["NumRegistroAnimaciones"] == null)
            {
                Session["NumRegistroAnimaciones"] = 0;
            }
            int numRegistro = (int)Session["NumRegistroAnimaciones"];
            numRegistro += 2;
            Session["NumRegistroAnimaciones"] = numRegistro;
            return RedirectToAction("AdministrarAnimaciones");
        }

        public ActionResult AdministrarIlustraciones()
        {
            if (Session["username"] != null)
            {
                if (Session["NumRegistroIlustraciones"] == null)
                {
                    Session["NumRegistroIlustraciones"] = 0;
                }
                List<Media> ilustraciones = mediaModel.GetIlustracionesPaginated((int)Session["NumRegistroIlustraciones"]);

                return View(ilustraciones);
            }
            else
            {
                return RedirectToAction("IniciarSesion");
            }
        }

        // GET: ResetNumPaginaAdminIlustraciones()
        public ActionResult ResetNumPaginaAdminIlustraciones()
        {
            Session["NumRegistroIlustraciones"] = null;
            return RedirectToAction("AdministrarIlustraciones");
        }

        // GET: SiguientePaginaAdminIlustraciones()
        public ActionResult SiguientePaginaAdminIlustraciones()
        {
            if (Session["NumRegistroIlustraciones"] == null)
            {
                Session["NumRegistroIlustraciones"] = 0;
            }
            int numRegistro = (int)Session["NumRegistroIlustraciones"];
            numRegistro += 8;
            Session["NumRegistroIlustraciones"] = numRegistro;
            return RedirectToAction("AdministrarIlustraciones");
        }

        public ActionResult AñadirAnimacionesoIlustraciones()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("IniciarSesion");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult AñadirAnimacionesoIlustraciones(MediaViewModel datos)
        {
            bool error = false;
            try
            {
                if (ModelState.IsValid)
                {
                    if (mediaModel.AñadirMedia(datos))
                    {
                        HttpPostedFileBase file = datos.Ubicacion;

                        if (file.ContentLength > 0 && file.ContentLength <= 41943000)
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            if (datos.Tipo == 1)
                            {
                                var path = Path.Combine(Server.MapPath("~/Recursos/uploads/Ilustraciones"), fileName);
                                file.SaveAs(path);
                            }
                            else if (datos.Tipo == 2)
                            {
                                var path = Path.Combine(Server.MapPath("~/Recursos/uploads/Animaciones"), fileName);
                                file.SaveAs(path);
                            }
                        }
                    }
                    else
                    {
                        error = true;
                    }
                }
                else
                {
                    error = true;
                }
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine(e);
                error = true;
            }

            if (error)
            {
                return RedirectToAction("Error");
            }
            else
            {
                return RedirectToAction("PanelDeControl");
            }
        }

        public ActionResult EditarAnimacion(int id)
        {
            if (Session["username"] != null)
            {
                Media animacion = mediaModel.GetMedia(id);
                return View(animacion);
            }
            else
            {
                return RedirectToAction("IniciarSesion");
            }
        }

        public ActionResult EditarIlustracion(int id)
        {
            if (Session["username"] != null)
            {
                Media ilustracion = mediaModel.GetMedia(id);
                return View(ilustracion);
            }
            else
            {
                return RedirectToAction("IniciarSesion");
            }
        }

        [HttpPost]
        public ActionResult Editar(Media datos)
        {
            bool error = false;
            try
            {   /*
                if (ModelState.IsValid)
                {
                    
                }
                else
                {
                    error = true;
                }*/
                if (!mediaModel.EditarMedia(datos))
                {
                    error = true;
                }
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine(e);
                error = true;
            }

            if (error)
            {
                return RedirectToAction("Error");
            }
            else
            {
                return RedirectToAction("PanelDeControl");
            }
        }
        
        public ActionResult Borrar(int id)
        {
            if (Session["username"] != null)
            {
                Media mediaDB = mediaModel.GetMedia(id);
                if(mediaModel.DeleteMedia(mediaDB))
                {
                    
                    if ((System.IO.File.Exists("~/Recursos/uploads/Ilustraciones/" + mediaDB.Ubicacion)))
                    {
                        System.IO.File.Delete("~/Recursos/uploads/Ilustraciones/" + mediaDB.Ubicacion);
                    }
                    else if ((System.IO.File.Exists("~/Recursos/uploads/Animaciones/" + mediaDB.Ubicacion)))
                    {
                        System.IO.File.Delete("~/Recursos/uploads/Animaciones/" + mediaDB.Ubicacion);
                    }
                    return RedirectToAction("PanelDeControl");
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            else
            {
                return RedirectToAction("IniciarSesion");
            }
        }

        public ActionResult Error()
        {
            return View();
        }
    }
}

SuffoArt/Controllers/PrincipalController.cs
using SuffoArt.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuffoArt.Controllers
{
    public class PrincipalController : Controller
    {
        MediaBD mediaModel = new MediaBD();

        // GET: Inicio
        public ActionResult Inicio()
        {
            return View();
        }

        // GET: Bio
        //public ActionResult Bio()
        //{
        //    return View();
        //}

        // GET: Animacion
        public ActionResult Animacion()
        {
            if (Session["NumRegistroAnimaciones"] == null)
            {
                Session["NumRegistroAnimaciones"] = 0;
            }
            List<Media> animaciones = mediaModel.GetAnimacionesPaginated((int)Session["NumRegistroAnimaciones"]);

            return View(animaciones);
        }

        // GET: ResetNumPaginaAnimacion()
        public ActionResult ResetNumPaginaAnimacion()
        {
            Session["NumRegistroAnimaciones"] = null;
            return RedirectToAction("Animacion");
        }

        // GET: SiguientePaginaAdminAnimacion()
        public ActionResult SiguientePaginaAnimacion()
        {
            if (Session["NumRegistroAnimaciones"] == null)
            {
                Session["NumRegistroAnimaciones"] = 0;
            }
            int numRegistro = (int)Session["NumRegistroAnimaciones"];
            numRegistro += 2;
            Session["NumRegistroAnimaciones"] = numRegistro;
            return RedirectToAction("Animacion");
        }

        // GET: Ilustracion
        public ActionResult Ilustracion()
        {
            if (Session["NumRegistroIlustraciones"] == null)
            {
                Session["NumRegistroIlustraciones"] = 0;
            }
            List<Media> ilustraciones = mediaModel.GetIlustracionesPaginated((int)Session["NumRegistroIlustraciones"]);

            return View(ilustraciones);
        }

        // GET: ResetNumPaginaIlustracion()
        public ActionResult ResetNumPaginaIlustracion()
        {
            Session["NumRegistroIlustraciones"] = null;
            return RedirectToAction("Ilustracion");
        }

        // GET: SiguientePaginaIlustraciones()
        public ActionResult SiguientePaginaIlustracion()
        {
            if (Session["NumRegistroIlustraciones"] == null)
            {
                Session["NumRegistroIlustraciones"] = 0;
            }
            int numRegistro = (int)Session["NumRegistroIlustraciones"];
            numRegistro += 8;
            Session["NumRegistroIlustraciones"] = numRegistro;
            return RedirectToAction("Ilustracion");
        }

        // GET: Blog
        //public ActionResult Blog()
        //{
        //    return View();
        //}

        // GET: Contacto
        public ActionResult Contacto()
        {
            return View();
        }
    }
}

SuffoArt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SuffoArt</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/CSS/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    @*
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                    </ul>
                </div>
            </div>
        </div>

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>
    *@
    <nav class="container-fluid fixed-top">
        <div class="row">
            @Html.ActionLink("Iniciar/Cerrar Sesión", "IniciarSesion", "Admin", new { area = "" }, new { @class = "nav-link col-sm-4" })
            @Html.ActionLink("Inicio", "Inicio", "Principal", new { area = "" }, new { @class = "nav-link text-center col-sm-4" })
            @Html.ActionLink("Panel de Control", "PanelDeControl", "Admin", new { area = "" }, new { @class = "nav-link text-right col-sm-4" })
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
        <footer class="container-fluid fixed-bottom pb-2">
            <nav class="nav justify-content-center align-bottom" id="nav_principal">
                @*@Html.ActionLink("bio", "Bio", "Principal", new { area = "" }, new { @class = "nav-link" })*@
                @Html.ActionLink("animación", "Animacion", "Principal", new { area = "" }, new { @class = "nav-link" })
                @Html.ActionLink("ilustración", "Ilustracion", "Principal", new { area = "" }, new { @class = "nav-link" })
                @*@Html.ActionLink("blog", "Blog", "Principal", new { area = "" }, new { @class = "nav-link" })*@
                @Html.ActionLink("contacto", "Contacto", "Principal", new { area = "" }, new { @class = "nav-link" })
            </nav>
            <div class="row">
                <div class="col-6 text-muted">&copy; @DateTime.Now.Year - Paula Fernández Suffo</div>
                <div class="col-6 text-muted text-right">Web creada por: Ricardo Fernández Cuesta</div>
            </div>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/JS/Site.js"></script>
</body>
</html>